### ISSUE TITLE
Error: Could not find or load main class MnistSD19Preprocess

### ISSUE THREAD

**Issue by Shivam60** [ProjectAGI/Preprocess_NIST_SD19#1]
if i build/compile the program, i get the following error.

Error: Could not find or load main class MnistSD19Preprocess

note: instead of passing arguments, i have give values of my source vairable and target variable directly.
i build the file with command on javac MnistSD19Preprocess.java
and when i compile it with java MnistSD19Preprocess.
i get Error: Could not find or load main class MnistSD19Preprocess as an error.
system: ubuntu 16.04 

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by googleknight** [comment]
If you have given variables value directly, then just go to src folder, open terminal there, type `javac .\mnist\MnistSD19Preprocess.java` press enter then type `java mnist.MnistSD19Preprocess`.

**Comment by Shivam60** [comment]
thanks for the help:)
